/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    Cell: typeof import('./../src/components/Cell/index.vue')['default']
    Greet: typeof import('./../src/components/Greet.vue')['default']
    Layout: typeof import('./../src/components/Layout/index.vue')['default']
    Leftbar: typeof import('./../src/components/Layout/leftbar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCardMeta: typeof import('naive-ui')['NCardMeta']
    NDivider: typeof import('naive-ui')['NDivider']
    NDivier: typeof import('naive-ui')['NDivier']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NTable: typeof import('naive-ui')['NTable']
    ResizeTrack: typeof import('./../src/components/ResizeTrack/index.vue')['default']
    ResizeTracker: typeof import('./../src/components/ResizeTracker/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
